services:
  - type: web
    name: fruitshub-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_SECRET
        generateValue: false
        value: FH_ADMIN_ROOT_SECRET_2026
      - key: SIGNING_SECRET
        generateValue: true
      - key: MIN_WAIT_SECONDS
        value: 20
      - key: KEY_DURATION_HOURS
        value: 24
      - key: TURSO_DATABASE_URL
        value: libsql://fruitshub-juanjopolo25.aws-ap-northeast-1.turso.io
      - key: TURSO_AUTH_TOKEN
        value: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODg5NTUxNzIsImlkIjoiMDFhMDg2MDktNDIwMS03YzNjLThiOGYtY2E0NWEyMDY2MWNmIiwia2lkIjoiM2J4RFc3R0lCS0dhWDFWV3h3YWFmQ1AxMm1aaXd6dXVmOUY5WW9iTjVLayIsInJpZCI6ImQwMjg3M2NhLWU3MTUtNDI4MS04NDk0LWQ1ODcxNTc1MmFkNCJ9.0DGWilrthpwMxAAHvghYLwyqsjF8VXsUKYuKV6m7PiLwOmJqljLKFbL-ErgrfWJJwv3TUq5rv-hiSjzg2zdtCA
